### ISSUE TITLE
Incorrect settings file loaded

### ISSUE THREAD

**Issue by Giorgi** [linmasaki/NLog.Appsettings.Standard#2]
Instead of `Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")` the library should be using `IHostingEnvironment.EnvironmentName` to load the correct settings file.

**Comment by linmasaki** [comment]
Thank you for your kind response, but I don't understand what's the difference between the two and what situation the library would load incorrect appsettings file?

**Comment by Giorgi** [comment]
I will try to explain it in a better way.

I am trying to read value from `appsettings.Production.json` file. The library calls `Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")` to determine the json file to load but it returns an empty string so it tries to load appsettings..json file (notice the two dots) instead of `appsettings.Production.json`.

As for ASP.NET Core itself it uses [env.EnvironmentName](https://github.com/aspnet/AspNetCore/blob/master/src/DefaultBuilder/src/WebHost.cs#L166) to determine which file to load and the default value of [HostingEnvironment.EnvironmentName](https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/Internal/HostingEnvironment.cs#L10) is **Production** so it loads correct file.

I think the best option is to have a public static property of `IConfiguration` type so that the library does not have to load any configuration file at all and we can set it from the value provided by DI in Startup class.

You could probably also inherit from [AspNetLayoutRendererBase](https://github.com/NLog/NLog.Web/blob/master/NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs#L18) and use `ServiceProvider` to resolve `IConfiguration` so that we do not need to set it but I haven't tested it.

**Comment by linmasaki** [comment]
Thank you for your detailed explanation.

It seems that what you mean is that there is only `appsettings.Production.json` in your project and there is no `appsettings.json`.

My expectation is that when the environment variable is set incorrectly or not set, `appsettings.json` will be used automatically, even though it is read as `appsettings..json`(because this file is not exist).

So is there anything wrong with my understanding above?

**Comment by Giorgi** [comment]
I have both files but my connection string is only in `appsettings.Production.json` because I have different connection strings in different environments.

I would not say that the environment variable is set incorrectly because there is no need for me to set it. In my opinion if the ASP.NET Core is able to load the config file so should the library.

**Comment by linmasaki** [comment]
That's strange, I have never encountered this problem like yours, I also have several config file and use them in different environments.

If you are convenient, could you give me a sample code let me to trigger a similar situation or give me some tip for it? I sincerely hope to solve your problem.




By the way, I think of a solution, but I don't think it is very good. The default value of [HostingEnvironment.EnvironmentName](https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/Internal/HostingEnvironment.cs#L10) is `Production`, so I can check whether `Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")` is empty in constructor. If it is empty, I will set the value to `Production`.

What do you think?

**Comment by linmasaki** [comment]
I think of a solution, but I don't think it is very good. The default value of [HostingEnvironment.EnvironmentName](https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/Internal/HostingEnvironment.cs#L10) is Production, so I can check whether 'Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")' is empty in constructor. If it is empty, I will set the value to 'Production'.

What do you think?

**Comment by Giorgi** [comment]
I think it will be better if you add a public setter for `_configurationRoot`. That way you won't need to load any file at all and the caller will pass the configuration they have. An even better option will be if you manage to retrieve it yourself probably by inheriting from `AspNetLayoutRendererBase` and resolving it from DI.

**Comment by linmasaki** [comment]
Could you give me a PR or code snippet, I am afraid that I misunderstood what you mean. Thanks.

**Comment by Giorgi** [comment]
OK, it looks like you can't access `ServiceProvider` as it is internal class. What about creating public setter for `_configurationRoot` ?

**Comment by linmasaki** [comment]
OK. Maybe I got your point now, I will update it and release it to a new version recently. Thank you for your patient explanation to me.

**Comment by Giorgi** [comment]
Also, you can make it of `IConfiguration` as you don't need any properties that `IConfigurationRoot` provides.

**Comment by Giorgi** [comment]
Thanks for the update, it works fine
